### ISSUE TITLE
Webauthn\\PublicKeyCredentialDescriptor::__construct() must be of the type string, null given

### ISSUE THREAD

**Issue by kabircse** [m1guelpf/laravel-fastlogin#33]
I am getting some errors on this package implementation. Have you any idea, where is my mistate ?

**on fastlogin/login/details:**
               Argument 2 passed to Webauthn\PublicKeyCredentialDescriptor::__construct() must be of the type string, null given, called in D:\laragon\www\face-test\vendor\m1guelpf\laravel-fastlogin\src\Http\Controllers\FastLoginController.php on line 116 {"userId":1,"exception":"[object] (TypeError(code: 0): Argument 2 passed to Webauthn\\PublicKeyCredentialDescriptor::__construct() must be of the type string, null given, called in D:\\laragon\\www\\face-test\\vendor\\m1guelpf\\laravel-fastlogin\\src\\Http\\Controllers\\FastLoginController.php on line 116 at D:\\laragon\\www\\face-test\\vendor\\web-auth\\webauthn-lib\\src\\PublicKeyCredentialDescriptor.php:49)
               
**And console showing:**
TypeError: Cannot read properties of undefined (reading 'replace')
    at base64UrlDecode (app.js:60:8)
    at preparePublicKeyOptions (app.js:81:7)               
               
               
**And my js code:**               
                    
                      const token = $('meta[name="csrf-token"]').attr('content');  
                    useLogin({
                        actionUrl: 'http://127.0.0.1:8000/fastlogin/login',
                        optionsUrl: 'http://127.0.0.1:8000/fastlogin/login/details',
                        actionHeader: {
                            'X-CSRF-TOKEN': token
                        },
                        optionsHeader: {
                            'X-CSRF-TOKEN': token
                        }
                    }, {
                        'X-CSRF-TOKEN': token
                    })().then((response) => {
                        //window.location.reload()
                        console.log(response + ', Login successful.');
                    })
                    .catch((error) => console.log(error, 'Login failed.'));

**Comment by kabircse** [comment]
@patrocle Any idea ?
